<?php
/**
 * Created by PhpStorm.
 * User: dell-annt
 * Date: 3/22/2019
 * Time: 2:44 PM
 */

namespace Slider\Providers;

use Illuminate\Support\Facades\Route;
use App\Providers\RouteServiceProvider as ServiceProvider;

Class RouteProvider extends ServiceProvider
{
    protected $namespace = 'Slider\Http\Controllers';
    public function boot()
    {
        Route::pattern('id', '[0-9]+');
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function map()
    {
        $this->mapWebRoutes();
        $this->mapApiRoutes();
    }

    protected function mapWebRoutes()
    {
        Route::group([
            'middleware' => ['web'],
            'namespace' => $this->namespace
        ], function ($router) {
            require __DIR__ . '/../../routes/web.php';
        });
    }

    protected function mapApiRoutes()
    {
        Route::group([
            'middleware' => 'api',
            'namespace' => $this->namespace,
            'prefix' => 'v1'
        ], function ($router) {
            require __DIR__ . '/../../routes/api.php';
        });
    }
}